config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :days do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'days#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :day
end

app/models/day.rb
class Day < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    validates :start_time, presence: true
    mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :day
  belongs_to :user
  validates_uniqueness_of :day_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :days, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_days, through: :likes, source: :day
  has_many :comments, dependent: :destroy
  def already_liked?(day)
    self.likes.exists?(day_id: day.id)
  end
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

    def create
      day = Day.find(params[:day_id])
      comment = day.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
    def index
        @days = Day.all
    end
    
    def new
        @day = Day.new
      end
    
      def create
        day = Day.new(day_params)

        day.user_id = current_user.id
        if day.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @day = Day.find(params[:id])
        @comments = @day.comments
        @comment = Comment.new
      end
    
      def edit
        @day = Day.find(params[:id])
      end

      def update
        day = Day.find(params[:id])
        if day.update(day_params)
          redirect_to :action => "show", :id => day.id
        else
          redirect_to :action => "new"
        end
      end
      
      def destroy
        day = Day.find(params[:id])
        day.destroy
        redirect_to action: :index
      end
    
      private
      def day_params
        params.require(:day).permit(:body, :start_time, :image)
      end
    end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(day_id: params[:day_id]) #user_idとday_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(day_id: params[:day_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/days/edit.html.erb
<div class = "edit">
  <%= form_for @day do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>
 </div> 

app/views/days/index.html.erb
<body class="user4">
<div class="index_all">

 <%= month_calendar events: @days do |date, days| %>
  <%= date.day%>
  <% days.each do |day| %>
    <div>
      <%= link_to day.body ,day_path(day.id) %>
    </div>
    <div class="days-content">
      <%= image_tag day.image_url, size: "50x40" if day.image? %>
    </div>

  <% end %>
 <% end %>


<div class="post_all">
  <h3>day一覧</h3>
  <div class="days-container">
    <% if user_signed_in? %>
    <% end %>
      <% @days.each do |t| %>
        <div class="day">
        <div class="days-content">
            <%= image_tag t.image_url, size: "250x200" if t.image? %>
        </div>
          <div class="days-command">   
          <%= t.user.email %>
              <%= t.body %>
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                  <%= link_to day_like_path(id: t.id, day_id: t.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% else %>
                  <%= link_to day_likes_path(id: t.id, day_id: t.id), method: :post do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% end %>
            <% else %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>

              <%= t.created_at %>
              <%= link_to "詳細へ", day_path(t.id) %>
              <%= link_to "編集する", edit_day_path(t.id) %>
              <%= button_to "削除する", day_path(t.id), method: :delete %>
            </div>
        </div>
      <% end %>
  </div>
  </div>
 
</div>
</div>

app/views/days/new.html.erb
<body class="user3">
<div class="new-page">
  <h1>服装日記</h1>
  <div class="h3">day</div>
  <%= form_for @day do |f| %>






    <div class="field">
      <%= f.label :body  %>
      <%= f.text_area :body, :size => "30x2" %>
    </div>

    <div class="time">
      <%= f.label :start_time %>
      <%= f.datetime_select :start_time %>
    </div>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <%= f.submit "投稿する" %>
  <% end %>
 
 <%= link_to "一覧に戻る", days_path %>
</div>

app/views/days/show.html.erb
<body class="user2">
<div class="show_all">
  <h1>Days</h1>
  <h3>Day詳細</h3>
  <div class="day">
    <p><%= @day.body %></p>
    <p><%= @day.created_at %></p>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(@day) %>
          <%= link_to day_like_path(@day), method: :delete do %>
              <i class="fas fa-heart"></i><%= @day.likes.count %>
          <% end %>
        <% else %>
          <%= link_to day_likes_path(@day), method: :post do %>
            
              <i class="fas fa-heart"></i><%= @day.likes.count %>
          <% end %>
        <% end %>
      <% else %>
      <i class="fas fa-heart"></i><%= @day.likes.count %>
      <% end %>
    <%= link_to "編集する", edit_day_path(@day.id) %>
  </div>

  <p>
    <strong>時間</strong>
    <%= @day.start_time.strftime("%Y-%m-%d %H:%M") %>
  </p>

  <h2>いいねしたユーザー</h2>
  <% @day.liked_users.each do |user| %>
    <li><%= user.email %></li>
  <% end %>

  <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
        <br>
    <% end %>

    <% if user_signed_in? %>
      <%= form_with(model: [@day, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= link_to "Day一覧に戻る", days_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Days</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f1f36a12bf.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="home">
      <%=link_to days_path do %>
        <%= image_tag 'title.png', alt: "day", class: "rogo" %>
      <%end%>
    </div>
    <div class="header-list">
      <div class="post">
          <% if user_signed_in? %>
            <%= link_to new_day_path, class: "btn btn btn-secondary text-white", method: :get do %>
             <i class="fa-regular fa-calendar-plus"></i>
            <% end %>
          <% end %>
        
      </div>
      <div class="log">
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, class: "btn btn btn-secondary text-white", method: :delete do %>
              <i class="fa-solid fa-right-from-bracket"></i>
            <% end %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path %></li>
            <%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
      </div>
      <div class="mypage_link">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user.id), class: "btn btn btn-secondary text-white", method: :get do %>
          <i class="fa-solid fa-user" style="color: #000;"></i>
        <% end %>
      <% end %>
      </div>
    </div>
  </header>
  <main>
   <%= yield %>
  </main>
 </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table-table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<body class="user1">
<div class="users_show_all">
  <h1>マイページ</h1>
  <p>名前 : <%= @user.name %></p>
  <br>
  <p>メールアドレス : <%= @user.email %></p>
  <br>
  <p>プロフィール : <%= @user.profile %></p>
  <br>
  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
  <% end %>

  <h2>ユーザーの投稿一覧</h2>
  <% @user.days.each do |t| %>
    <%= t.user.name %>
    <%= t.body %>
  <% end %>

  <!-- 以下はいいね機能を実装している場合-->
  <h2>ユーザーがいいねした投稿一覧</h2>
  <% @user.liked_days.each do |t| %>
    <%= t.user.name %>
    <%= t.body %>
  <% end %>
  <!-- ここまで-->

  <%= link_to "Day一覧に戻る", days_path %>
</div>
</div>